env:
  node: true
  browser: true
  jest: true

plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'

rules:
  import/extensions: 0
  react/prop-types: 0

parserOptions:
  ecmaVersion: 12
  sourceType: module

settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
